### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by azizkeremozkan** [tbuehler/pSpectralClustering#4] opened 2022-03-08 08:30 UTC
Hello, when i try this code using its ratio cut option with the command;
[clusters,cuts,cheegers] = pSpectralClustering(30x30_adjacency_matrix, 2, false, 15);
i get the following error;

![p-SpectralClustering-error](https://user-images.githubusercontent.com/16885932/157197491-4290b044-8b80-44b8-85b7-966c15b4ce2c.png)

**Comment by tbuehler** [comment] 2022-03-08 12:51
Hi, it seems there was an interface change to the eigs function in a recent update. Which Matlab version are you using?

**Comment by azizkeremozkan** [comment] 2022-03-08 16:30
R2021a

**Comment by tbuehler** [comment] 2022-03-09 21:44
I am not able to reproduce the error. Could you please share your input matrix with me?

**Comment by azizkeremozkan** [comment] 2022-03-10 11:22
[adjacency_matrix.mat.zip](https://github.com/tbuehler/pSpectralClustering/files/8222896/adjacency_matrix.mat.zip)
The adjacency matrix is in .mat file, thank you.

**Comment by tbuehler** [comment] 2022-03-10 21:12
I made some changes in the develop branch. There was an issue with the multi-partitioning scheme, it did not stop when the cluster had size 1. Could you please check if everything works now on your end? Thanks.

**Comment by azizkeremozkan** [comment] 2022-03-11 08:01
It works now, thank you.

**Comment by tbuehler** [comment] 2022-03-11 19:50
Great! Thank you for pointing out this error!
I will then merge the code and close this issue.

**Closed as completed by tbuehler** 2022-03-11 19:50 UTC
